name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
        # -------------------------------------------------------
        # 1. Checkout Code
        # -------------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

        # -------------------------------------------------------
        # 2. Set up Go Environment
        # -------------------------------------------------------
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

        # -------------------------------------------------------
        # 3. Linting (GolangCI-Lint)
        # -------------------------------------------------------
      - name: Run Linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m

        # -------------------------------------------------------
        # 4. SAST - CodeQL
        # -------------------------------------------------------
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: go

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

        # -------------------------------------------------------
        # 5. SCA - Go Vulncheck (Golang Dependency Scanning)
        # -------------------------------------------------------
      - name: SCA (Go Vulncheck)
        uses: golang/govulncheck-action@v1

        # -------------------------------------------------------
        # 6. Unit Testing
        # -------------------------------------------------------
      - name: Run Unit Tests
        run: go test -v ./...

        # -------------------------------------------------------
        # 7. Build Application
        # -------------------------------------------------------
      - name: Build Application
        run: go build -v ./...

        # -------------------------------------------------------
        # 8. Docker Build
        # -------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener-devops:latest .

        # -------------------------------------------------------
        # 9. Trivy - Container Image Security Scanning
        # -------------------------------------------------------
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/url-shortener-devops:latest'
          scan-type: 'image'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

        # -------------------------------------------------------
        # 10. Docker Container Basic Testing
        # -------------------------------------------------------
      - name: Run container and test
        run: |
          docker run -d --name test-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener-devops:latest
          sleep 5
          curl --fail http://localhost:8080/health || exit 1
          docker stop test-container
          docker rm test-container

        # -------------------------------------------------------
        # 11. Login to Docker Hub
        # -------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # -------------------------------------------------------
        # 12. Push Docker Image to Docker Hub
        # -------------------------------------------------------
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener-devops:latest